### ISSUE TITLE
card sorting bug 

### ISSUE THREAD

**Issue by a98ccp** [kikychow/poker-wordle#4]
on today's challenge, the solution is  not sort by the order suggested, please view the image below.
<img width="395" alt="Screenshot 2022-03-23 at 9 43 12 AM" src="https://user-images.githubusercontent.com/7104363/159605606-0623e266-d875-471e-8d7b-59dce8d19a91.png">

**Comment by kikychow** [comment]
@a98ccp Hi, the cards are first sorted in order of quads, triples, pairs and singles, and then in the order of rankings from highest to lowest. In this case, the trips should go before the pair in a full house. More examples are given in the card order menu. I hope it's clear for you!
